package com.xproject.master.app.dataprovider.mercadolivre.dto;

import java.util.List;
import lombok.Data;

@Data
public class ProductItemDto{
	private Object originalPrice;
	private List<Object> coverageAreas;
	private String secureThumbnail;
	private Boolean catalogListing;
	private String buyingMode;
	private List<Object> dealIds;
	private List<Object> descriptions;
	private Integer availableQuantity;
	private String domainId;
	private Shipping shipping;
	private Integer price;
	private Object officialStoreId;
	private String warranty;
	private Object sellerContact;
	private String id;
	private Integer sellerId;
	private Boolean acceptsMercadopago;
	private String thumbnail;
	private String lastUpdated;
	private Boolean automaticRelist;
	private List<String> tags;
	private String startTime;
	private String condition;
	private List<String> channels;
	private Object subtitle;
	private String siteId;
	private String permalink;
	private Object differentialPricing;
	private String status;
	private String stopTime;
	private String title;
	private Integer soldQuantity;
	private List<PicturesItem> pictures;
	private String categoryId;
	private List<Object> variations;
	private Integer basePrice;
	private List<SaleTermsItem> saleTerms;
	private List<Object> subStatus;
	private Integer initialQuantity;
	private String dateCreated;
	private List<Object> warnings;
	private List<Object> nonMercadoPagoPaymentMethods;
	private Object catalogProductId;
	private Double health;
	private String listingSource;
	private SellerAddress sellerAddress;
	private String internationalDeliveryMode;
	private String thumbnailId;
	private Object parentItemId;
	private Location location;
	private List<AttributesItem> attributes;
	private String listingTypeId;
	private String currencyId;
	private Object videoId;
}