create table TB_CLIENT(id int8 generated by default as identity, name varchar(255), surname varchar(255), phone varchar(255),age varchar(255),phoneType varchar(255), primary key (id));
INSERT INTO TB_CLIENT(name, surname, phone, age, phoneType ) VALUES ('maria', 'silva', '9999999999', 30 ,'Pessoal');
INSERT INTO TB_CLIENT(name, surname, phone, age, phoneType ) VALUES ('joao', 'silva', '9999999999', 30 ,'Pessoal');
INSERT INTO TB_CLIENT(name, surname, phone, age, phoneType ) VALUES ('ana', 'silva', '9999999999', 30 ,'Pessoal');
INSERT INTO TB_CLIENT(name, surname, phone, age, phoneType ) VALUES ('lucia', 'silva', '9999999999', 30 ,'Pessoal');
INSERT INTO TB_CLIENT(name, surname, phone, age, phoneType ) VALUES ('joaquim', 'silva', '9999999999', 30 ,'Pessoal');
