version: '3'

services:

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "15432:5432"
        volumes:
            - dbdata:/data/pgdb
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"

    mongo:
        container_name: mongo
        image: mongo:4.4.4
        restart: always
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/mongodb
#            - dbdata:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_DATABASE: masterdb

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 9081:8081
        volumes:
            - dbdata:/data/db
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo_dev

    redis:
        container_name: redis
        image: redis
        hostname: redis
        restart: always
        command: redis-server
        ports:
            - "6379:6379"

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"

volumes:
    dbdata: