version: '3'

services:

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8082

    mongo:
        image: mongo:4.4.4
        container_name: mongo_dev
        restart: always
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
            - dbdata:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_DATABASE: masterdb

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongo
        ports:
            - 9081:8081
        volumes:
            - dbdata:/data/db
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo_dev

    redis:
        image: redis
        command: redis-server --requirepass 12345678
        ports:
            - "6379:6379"

volumes:
    dbdata: