version: '3.9'

services:

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - dbdata:/data/pgdb
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - 5050:80

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/mongodb
            - dbdata:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_DATABASE: xprojectdb
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: MongoExpress
        networks:
            -

    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: defaultuser
            ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: MongoExpress

    redis:
        container_name: redis
        image: redis
        hostname: redis
        restart: always
        command: redis-server
        ports:
            - 6379:6379

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8082:8082

volumes:
    dbdata:

networks:
    default:
        driver: custom-driver-1