version: '3'

services:

    db:
        image: mongo:4.4.4
        container_name: mongo_dev
        restart: always
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
            - dbdata:/docker-entrypoint-initdb.d
        environment:
            - MONGO_INITDB_DATABASE=masterdb
        networks:
            - compose-network

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - db
        ports:
            - 9081:8081
        volumes:
            - dbdata:/data/db
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo_dev
        networks:
            - compose-network

    redis:
        image: redis
        command: redis-server --requirepass 12345678
        ports:
            - "6379:6379"
        networks:
            - compose-network

volumes:
    dbdata:

networks:
    compose-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.111.0.0/16