version: '3.1'

services:

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/data/pgdb
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: xprojectdb
        networks:
            - xproject_network

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        networks:
            - xproject_network

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass12345
        networks:
            - xproject_network

    mongo-express:
        image: mongo-express
        restart: always
        links:
            - mongo
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass12345
            ME_CONFIG_MONGODB_SERVER: mongo
        volumes:
            - mongodb-data
        networks:
            - xproject_network

    redis:
        container_name: redis
        image: redis
        hostname: redis
        restart: always
        command: redis-server
        ports:
            - "6379:6379"
        networks:
            - xproject_network

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "9091:8081"
        networks:
            - xproject_network

volumes:
    mongodb-data:
    pg-data:

networks:
    xproject_network:
        driver: bridge